#app/llm/prompt_builder.py
def build_behavior_prompt(behavior_name: str, text: str) -> str:
    return (
        "You are a strict JSON generator and a behavior detection engine.\n\n"
        f"Your task:\nDetermine whether the operator performed the behavior: \"{behavior_name}\"\n\n"
        "Analysis rules:\n"
        "- Read the operator text carefully.\n"
        "- Decide if the behavior is clearly present, clearly not present, or unclear.\n\n"
        "Output rules (VERY IMPORTANT):\n"
        "- You MUST respond with ONLY a valid JSON object.\n"
        "- Do NOT include ANY explanation, comments, reasoning, markdown, or extra text.\n"
        "- Do NOT put text before or after the JSON.\n"
        "- Do NOT wrap the JSON in code blocks.\n"
        "The output MUST strictly follow this schema:\n\n"
        "{\n"
        "  \"label\": 1 | 0 | null,\n"
        "  \"confidence\": number\n"
        "}\n\n"
        "Definitions:\n"
        "- label = 1 → the behavior IS clearly present.\n"
        "- label = 0 → the behavior is clearly NOT present.\n"
        "- label = null → not enough information to decide.\n"
        "- confidence MUST be a float between 0.0 and 1.0.\n"
        "- confidence MUST always be present.\n\n"
        "If unsure, output:\n"
        "{ \"label\": null, \"confidence\": 0.0 }\n\n"
        "Operator Text:\n"
        "\"\"\"\n"
        f"{text}\n"
        "\"\"\"\n"
    )
