#app/core/errors.py
class ErrorCode:

    EMPTY_TRANSCRIPT = "EMPTY_TRANSCRIPT"
    NO_OPERATOR_SPEECH = "NO_OPERATOR_SPEECH"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"
    LLM_FAILURE = "LLM_FAILURE"
    LLM_UNAVAILABLE = "LLM_UNAVAILABLE"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    LLM_NON_JSON_OUTPUT = "LLM_NON_JSON_OUTPUT"
    LLM_SCHEMA_MISMATCH = "LLM_SCHEMA_MISMATCH"
    LLM_CALL_FAILED = "LLM_CALL_FAILED"
